# -*- coding: utf-8 -*-

keys_dict = {
    'D05.SI': 'DBS Group Holdings Ltd',
    'O39.SI': 'Oversea-Chinese Banking Corp Ltd',
    'U11.SI': 'United Overseas Bank Ltd',
    '^STI': 'STI',
    '^GSPC': 'SP500',
    '^VIX': 'VIX',
}

reits_dict = {
    'O5RU.SI': 'AIMS APAC REIT',
    'XZL.SI': 'ARA US Hospitality Trust',
    'A17U.SI': 'Ascendas REIT',
    'HMN.SI': 'Ascott Residence Trust',
    'BMGU.SI': 'BHG Retail REIT',
    'K2LU.SI': 'Cache Logistics Trust',
    'C61U.SI': 'CapitaLand Commercial Trust',
    'C38U.SI': 'Capitaland Mall Trust',
    'AU8U.SI': 'Capitaland Retail China Trust',
    'CNNU.SI': 'Cromwell European REIT',
    'J85.SI': 'CDL Hospitality Trust',
    'LIW.SI': 'Eagle US Hospitality Trust',
    'BWCU.SI': 'EC World REIT',
    'J91U.SI': 'ESR-REIT',
    'Q5T.SI': 'Far East Hospitality Trust',
    'AW9U.SI': 'First REIT',
    'J69U.SI': 'Frasers Centrepoint Trust',
    'ACV.SI': 'Frasers Hospitality Trust',
    'BUOU.SI': 'Frasers L&C Trust',
    'UD1U.SI': 'IREIT Global',
    'AJBU.SI': 'Keppel DC REIT',
    'CMOU.SI': 'Keppel Pacific Oak US RIET',
    'K71U.SI': 'Keppel REIT',
    'JYEU.SI': 'Lendlease Global Comm REIT',
    'D5IU.SI': 'Lippo Malls Indonesia Retail Trust',
    'BTOU.SI': 'Manulife US REIT',
    'RW0U.SI': 'Mapletree North Asia Commercial Trust',
    'ME8U.SI': 'Mapletree Industrial Trust',
    'M44U.SI': 'Mapletree Logistics Trust',
    'N2IU.SI': 'Mapletree Commercial Trust',
    'TS0U.SI': 'OUE Commercial REIT',
    'C2PU.SI': 'Parkway Life REIT',
    'OXMU.SI': 'Prime US REIT',
    'M1GU.SI': 'Sabana REIT',
    'CRPU.SI': 'Sasseur REIT',
    'SV3U.SI': 'Soilbuild Business Space REIT',
    'SK6U.SI': 'SPH REIT',
    'P40U.SI': 'Starhill Global REIT',
    'T82U.SI': 'Suntec REIT',
    'CJLU.SI': 'NetLink NBN Trust',
    'CY6U.SI': 'Ascendas India Trust',
}


etf_dict = {
    'ACWI': 'iShares MSCI ACWI ETF',
    'URTH': 'iShares MSCI World ETF', 
    'IEUR': 'iShares Core MSCI Europe ETF',
    'EEM': 'iShares MSCI Emerging Markets ETF',
    'AAXJ': 'iShares MSCI All Country Asia ex Jpn ETF',
    'VWRD.L': 'Vanguard FTSE ALL-WORLD', 
    'SPY': 'SPDR S&P 500 ETF',
    'ES3.SI': 'STI ETF',
    'G3B.SI': 'Nikko STI ETF',
    'BYI.SI': 'Phillip SGX APAC DIV REIT ETF',
    'CFA.SI': 'NikkoAM-STC Asia ex Japan REIT ETF',
    'CLR.SI': 'Lion-Phillip S-REIT ETF',
    'O87.SI': 'GLD US$',
    'A35.SI': 'ABF SG Bond ETF',
}


sti_dict = {
    'C32.SI': 'Capitaland Ltd',
    'C09.SI': 'City Developments Ltd',
    'C52.SI': 'ComfortDelgro Corporation Ltd',
    'D01.SI': 'Dairy Farm Intl Holdings Ltd',
    'D05.SI': 'DBS Group Holdings Ltd',
    'F99.SI': 'Fraser and Neave Ltd',
    'G13.SI': 'Genting Singapore Ltd',
    'G07.SI': 'Great Eastern Holding Ltd',
    'F17.SI': 'GuocoLand Limited',
    'H02.SI': 'Haw Par Corporation Ltd',
    'H13.SI': 'Ho Bee Land Ltd',
    'H78.SI': 'Hongkong Land Holdings Ltd',
    'C07.SI': 'Jardine Cycle & Carriage Ltd ',
    'J36.SI': 'Jardine Matheson Holdings Ltd',
    'J37.SI': 'Jardine Strategic Holdings Ltd',
    'BN4.SI': 'Keppel Corporation Ltd',
    'O32.SI': 'Olam International Ltd',
    'O39.SI': 'Oversea-Chinese Banking Corp Ltd',
    'BSL.SI': 'Raffles Medical Group Ltd',
    'S59.SI': 'SIA Engineering Company Ltd',
    'S58.SI': 'SATS Ltd',
    'U96.SI': 'SembCorp Industries Ltd',
    'S51.SI': 'Sembcorp Marine Ltd ',
    'OV8.SI': 'Sheng Siong Group Ltd',
    'S05.SI': 'Sim Lian Group Ltd ',
    'C6L.SI': 'Singapore Airlines Ltd',
    'S68.SI': 'Singapore Exchange Ltd',
    'S08.SI': 'Singapore Post Limited',
    'T39.SI': 'Singapore Press Holdings Ltd',
    'S63.SI': 'Singapore Technologies Engineering Ltd',
    'Z74.SI': 'Singtel',
    'CC3.SI': 'StarHub Ltd',
    'Y92.SI': 'Thai Beverage Public Company Ltd',
    'U14.SI': 'UOL Group Limited',
    'U11.SI': 'United Overseas Bank Ltd',
    'V03.SI': 'Venture Corporation Ltd',
    'BS6.SI': 'Yangzijiang Shipbuilding Holdings Ltd',
}
